### ISSUE TITLE
Related to:  Constant Velocity Joints !

### ISSUE THREAD

**Issue by MJx9977** [GuyApooye/ClockworkAdditions#10]
When we go out of range (3 blocks) then the connection between joint breaks ! 

And when we come near it again it doesn't reconnects automatically, We need to break and place the joints again !

Can we make it reconnectable when they come in range ?

**Comment by thetheaplant** [comment]
Working as intended.

**Comment by GuyApooye** [comment]
im reworking joints so theyll be constrained within range instead of breaking. some of the implementation should be on the 1.18.2 branch, its really buggy though and doesnt work so dont compile it.
