### ISSUE TITLE
Server still crashes even after the commit that tried to fix it, but differently.

### ISSUE THREAD

**Issue by Brickmaster1** [GuyApooye/ClockworkAdditions#13]
Caused by: java.lang. RuntimeException: Cannot load class net.fab ricmc.fabric. api . client . event.lifecycle . v1 .ClientTickEvents in e nvironment type SERVER

Is the error, so I think you're still using client features even though it's the server side.

**Comment by GuyApooye** [comment]
oh i know what it is

**Comment by GuyApooye** [comment]
i believe i fixed it

**Comment by Brickmaster1** [comment]
Alright, thanks, I will test

**Comment by Brickmaster1** [comment]
Can confirm you fixed it 👍
