### ISSUE TITLE
Copycat wings make ship fly away on contact with ground

### ISSUE THREAD

**Issue by Pecant-Pie** [GuyApooye/ClockworkAdditions#3]
Version info: Forge 1.20.1 version 0.0.6
with VS version 2.3.0-beta.5

I assembled a ship with a bunch of copy cat wings on it, and it just yeeted out of existence immediately.

So I assembled three copycat wings attached to three concrete blocks, and it jumped into the air and then floated back down, but kept getting faster and jumping higher until it went into the sky.

It seems like copycat flaps are much more stable when connected to heavier blocks, but if the ship is too light it will just disappear.

**Comment by GuyApooye** [comment]
The problem here is vs2. There is a jar with a version of vs2 that fixes this issue in the Tank Tussle server.

note: copycat wings weight too much but ill fix it someday
