### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by LMaxRouterCN** [GuyApooye/ClockworkAdditions#4]
[minecraft-exported-crash-info-2024-10-01T22-37-05.zip](https://github.com/user-attachments/files/17211460/minecraft-exported-crash-info-2024-10-01T22-37-05.zip)
I'm having a crash when placing a Constant Velocity Joint.

**Comment by LMaxRouterCN** [comment]
It took me three hours to finally troubleshoot the problem,It's the Cracker's Wither Storm Mod that's causing the crash, which I didn't anticipate.

**Comment by LMaxRouterCN** [comment]
[minecraft-exported-crash-info-2024-10-06T03-39-24.zip](https://github.com/user-attachments/files/17267325/minecraft-exported-crash-info-2024-10-06T03-39-24.zip)
The report is here.

**Comment by GuyApooye** [comment]
The problem is a really odd edge case and i have no idea why the wither storm mod would cause it. Ill fix it in the next update.

**Comment by LMaxRouterCN** [comment]
感谢🙏
