### ISSUE TITLE
Redstone gyro looks weird in PID mode

### ISSUE THREAD

**Issue by MulatramAwA** [GuyApooye/ClockworkAdditions#6]
Redstone gyro always let the output of the east be 15 when it's in PID mode.
![image](https://github.com/user-attachments/assets/da8fba21-5547-492a-960b-09be80fb3937)
It looks weird, I cannot find the problem in your code.
(Mod files is build from latest code on branch 1.20.1/main)

**Comment by GuyApooye** [comment]
PID really doesnt work because the math is probably all wrong in there.
Anyways, its best to not use any blocks with missing textures.

**Comment by MulatramAwA** [comment]
Magical eastern power

**Comment by MulatramAwA** [comment]
> PID really doesnt work, because the math is probably all wrong in there. Anyways, its best to not use any blocks with missing textures.

I guese the problem is on your PID‘s parameters.

**Comment by MulatramAwA** [comment]
#7 #8 Fixed
