### ISSUE TITLE
After adding to the server, the server will not start properly

### ISSUE THREAD

**Issue by KaliRin** [GuyApooye/ClockworkAdditions#9]
![abc](https://github.com/user-attachments/assets/6a5b8c2d-5738-4191-aeaa-fe2a842618d2)The Fabric server is used, and the version is 0.16.7

**Comment by GuyApooye** [comment]
Do you have create and clockwork?

**Comment by KaliRin** [comment]
> 你有 create 和 clockwork 吗？

Yes,of course,The version of clockwork is clockwork-1.20.1-0.1.16-fabric-b3b22e39fe，the creat is create-fabric-0.5.1-f-build.1417+mc1.20.1

**Comment by GuyApooye** [comment]
forgot a client check at init
